#!/usr/bin/env python3
"""
Parse the output of check_adaptors.py and write a LaTeX table snippet.
Usage: python adaptor_check_table.py <adaptor_check.txt> <output.tex>
"""
import re
import sys


def parse_results(path):
    """Parse the text output of check_adaptors.py into a list of row dicts.

    Args:
        path: Path to the adaptor_check.txt file produced by check_adaptors.py.

    Returns:
        List of dicts with keys 'label', 'r1_count', 'r1_pct', 'r2_count', 'r2_pct'.
        Percentages are already LaTeX-escaped (% → \\%).
    """
    rows = []
    with open(path) as f:
        for line in f:
            # Match data rows: label, r1_count, r1_pct, r2_count, r2_pct
            m = re.match(
                r"^(Adp\d\s+\(\w+\))\s+([\d,]+)\s+([\d.]+%)\s+([\d,]+)\s+([\d.]+%)",
                line.strip()
            )
            if m:
                rows.append({
                    "label":    m.group(1).strip(),
                    "r1_count": m.group(2),
                    "r1_pct":   m.group(3).replace("%", "\\%"),  # escape for LaTeX
                    "r2_count": m.group(4),
                    "r2_pct":   m.group(5).replace("%", "\\%"),  # escape for LaTeX
                })
    return rows


def is_dominant(pct_str):
    """Return True if this percentage is notably high (>= 1%).

    Args:
        pct_str: Percentage string, optionally LaTeX-escaped (e.g. '2.3\\%').

    Returns:
        True if the numeric value is >= 1.0, False otherwise.
    """
    return float(pct_str.replace("\\%", "").replace("%", "")) >= 1.0


def fmt_cell(count, pct, dominant):
    """Bold the cell contents if it represents the dominant adaptor signal.

    Args:
        count: Read count string.
        pct:   Percentage string (LaTeX-escaped).
        dominant: If True, wrap both values in LaTeX \\textbf{}.

    Returns:
        Tuple of (formatted_count, formatted_pct) strings.
    """
    if dominant:
        return f"\\textbf{{{count}}}", f"\\textbf{{{pct}}}"
    return count, pct


def main(txt_path, tex_path):
    """Parse adaptor check results and write a LaTeX table snippet.

    Args:
        txt_path: Path to the adaptor_check.txt output of check_adaptors.py.
        tex_path: Destination path for the generated .tex table file.
    """
    rows = parse_results(txt_path)
    if not rows:
        print(f"ERROR: no data rows found in {txt_path}", file=sys.stderr)
        sys.exit(1)

    lines = [
        "% Auto-generated by pipeline/scripts/adaptor_check_table.py — do not edit manually.",
        "\\begin{table}[H]",
        "\\centering",
        "\\begin{tabular}{llrrrr}",
        "\\toprule",
        "\\textbf{Label} & \\textbf{Sequence (5'$\\to$3')} & "
        "\\textbf{R1 count} & \\textbf{R1\\,\\%} & "
        "\\textbf{R2 count} & \\textbf{R2\\,\\%} \\\\",
        "\\midrule",
    ]

    seq_map = {
        "Adp1    (fwd)": "AAGACTCGGCAGCATCTCCA",
        "Adp1 RC (rev)": "TGGAGATGCTGCCGAGTCTT",
        "Adp2    (fwd)": "GCGATCGTCACTGTTCTCCA",
        "Adp2 RC (rev)": "TGGAGAACAGTGACGATCGC",
    }

    for row in rows:
        dom_r1 = is_dominant(row["r1_pct"])
        dom_r2 = is_dominant(row["r2_pct"])
        r1_c, r1_p = fmt_cell(row["r1_count"], row["r1_pct"], dom_r1)
        r2_c, r2_p = fmt_cell(row["r2_count"], row["r2_pct"], dom_r2)
        seq = seq_map.get(row["label"], "")
        lines.append(
            f"\\texttt{{{row['label']}}} & \\texttt{{{seq}}} & "
            f"{r1_c} & {r1_p} & {r2_c} & {r2_p} \\\\"
        )

    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{Occurrence of both adaptor sequences and their reverse complements (RC)",
        "in R1 and R2 raw reads. Bold values indicate the dominant signal in each read.",
        "Adp2~RC is dominant in R1 and Adp1~RC is dominant in R2, confirming",
        "Scenario~B: the library uses different adaptors on each end (standard paired-end).}",
        "\\label{tab:adaptor-check}",
        "\\end{table}",
    ]

    with open(tex_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Written: {tex_path}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <adaptor_check.txt> <output.tex>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])
