#!/usr/bin/env python3
"""
amplicon_length_table.py
Build a LaTeX table of amplicon, primer, insert, and R1/R2 overlap lengths.

Primer lengths come from config.yaml; amplicon lengths from the combined
(strict + relaxed) BLAST primer table.

Usage: amplicon_length_table.py <config.yaml> <blast_primer_table_relaxed.tex> <out.tex>
"""
import re
import sys

READ_LEN = 150   # MiSeq paired-end read length


def parse_amplicon_lengths(tex_path):
    """Extract amplicon lengths from the relaxed BLAST primer table TeX file.

    Args:
        tex_path: Path to the blast_primer_table_relaxed.tex file.

    Returns:
        Dict mapping amplicon number (int) to amplicon length in bp (int).
    """
    lengths = {}
    pattern = re.compile(r"\\texttt\{Amplicon (\d+)\}.*?(\d+)\\,bp")
    with open(tex_path) as fh:
        for line in fh:
            m = pattern.search(line)
            if m:
                lengths[int(m.group(1))] = int(m.group(2))
    return lengths


def parse_primer_seqs(config_path):
    """
    Minimal YAML parser for the primers section of config.yaml.
    Reads list items under primers.forward and primers.reverse.
    """
    fwd, rev = [], []
    current = None
    with open(config_path) as fh:
        for line in fh:
            stripped = line.strip()
            if stripped == "forward:":
                current = fwd
            elif stripped == "reverse:":
                current = rev
            elif stripped.startswith("- ") and current is not None:
                seq = stripped[2:].split("#")[0].strip()  # strip inline comments
                current.append(seq)
            elif stripped and not stripped.startswith("-") and ":" in stripped:
                # new top-level key — stop collecting
                if current is not None and stripped not in ("forward:", "reverse:"):
                    current = None
    return fwd, rev


def main(config_path, tex_path, out_path):
    """Generate a LaTeX table of amplicon, primer, insert, and overlap lengths.

    Args:
        config_path: Path to pipeline/config.yaml (for primer sequences).
        tex_path:    Path to blast_primer_table_relaxed.tex (for amplicon lengths).
        out_path:    Destination path for the generated .tex table file.
    """
    fwd_seqs, rev_seqs = parse_primer_seqs(config_path)
    amp_lengths = parse_amplicon_lengths(tex_path)

    rows = []
    for i, (fwd, rev) in enumerate(zip(fwd_seqs, rev_seqs), start=1):
        amp_len = amp_lengths.get(i)
        fwd_len = len(fwd)
        rev_len = len(rev)
        insert  = amp_len - fwd_len - rev_len if amp_len else None
        overlap = 2 * READ_LEN - amp_len      if amp_len else None
        rows.append((i, amp_len, fwd_len, insert, rev_len, overlap))

    with open(out_path, "w") as fh:
        fh.write("% Auto-generated by pipeline/scripts/amplicon_length_table.py\n")
        fh.write("% via rule amplicon_length_table\n")
        fh.write("\\begin{table}[H]\n")
        fh.write("\\centering\n")
        fh.write("\\begin{tabular}{lrrrrr}\n")
        fh.write("\\toprule\n")
        fh.write(
            "\\textbf{Amplicon} & "
            "\\textbf{Amp. length} & "
            "\\textbf{Fwd primer} & "
            "\\textbf{Insert} & "
            "\\textbf{Rev primer} & "
            "\\textbf{R1/R2 overlap} \\\\\n"
        )
        fh.write("\\midrule\n")
        for amp, amp_len, fwd_len, insert, rev_len, overlap in rows:
            fh.write(
                f"Amplicon~{amp} & "
                f"{amp_len}\\,bp & "
                f"{fwd_len}\\,bp & "
                f"{insert}\\,bp & "
                f"{rev_len}\\,bp & "
                f"{overlap}\\,bp \\\\\n"
            )
        fh.write("\\bottomrule\n")
        fh.write("\\end{tabular}\n")
        fh.write(
            "\\caption{Amplicon composition derived from BLAST primer coordinates "
            "(Table~\\ref{tab:blast-primers-relaxed}) and primer sequences "
            "(Table~\\ref{tab:primers}). "
            "Insert length $= l_\\mathrm{amp} - l_\\mathrm{fwd} - l_\\mathrm{rev}$. "
            "R1/R2 overlap $= 2r - l_\\mathrm{amp}$ where $r = 150$\\,bp; "
            "positive values indicate the two reads overlap in the centre of the "
            "amplicon (see Figure~\\ref{fig:amplicon-structure}).}\n"
        )
        fh.write("\\label{tab:amplicon-lengths}\n")
        fh.write("\\end{table}\n")

    print(f"Written: {out_path}", file=sys.stderr)


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <config.yaml> <blast_primer_table_relaxed.tex> <out.tex>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2], sys.argv[3])
