#!/usr/bin/env python3
"""
amplicon_unmapped_rate.py
Cross-references primer assignment across all read pairs and unmapped read
pairs to compute the per-amplicon unmapped rate.

For each amplicon (and the unassigned category) the table shows:
  - total read pairs assigned to that amplicon across the whole library
  - how many of those pairs failed to align to hg19
  - the unmapped fraction (%)

Usage:
    amplicon_unmapped_rate.py <all_r1> <all_r2> <unmapped_r1> <unmapped_r2> <output.tex>
"""
import gzip
import sys

AMPLICONS = [
    {"name": "Amplicon 1",
     "fwd": "TTGCCAGTTAACGTCTTCCTTCTCTCTCTG",
     "rev": "GAGAAAAGGTGGGCCTGAGGTTCAGAGCCA"},
    {"name": "Amplicon 2",
     "fwd": "CCCTTGTCTCTGTGTTCTTGTCCCCCCCA",
     "rev": "CCCCACCAGACCATGAGAGGCCCTGCGGCC"},
    {"name": "Amplicon 3",
     "fwd": "TGATCTGTCCCTCACAGCAGGGTCTTCTCT",
     "rev": "TGACCTAAAGCCACCTCCTTA"},
    {"name": "Amplicon 4",
     "fwd": "CACACTGACGTGCCTCTCCCTCCCTCCA",
     "rev": "CCGTATCTCCCTTCCCTGATTA"},
]

MAX_MISMATCHES = 2
PREFIX_LEN     = 20


def hamming(a, b):
    """Count mismatches between two strings up to the length of the shorter one.

    Args:
        a: First sequence string.
        b: Second sequence string.

    Returns:
        Number of positions where the characters differ.
    """
    return sum(x != y for x, y in zip(a, b))


def assign_amplicon(seq, primers):
    """Assign a read sequence to the best-matching primer by Hamming distance.

    Compares the first PREFIX_LEN bases of seq against the first PREFIX_LEN
    bases of each primer and returns the index of the closest match, provided
    it is within MAX_MISMATCHES.

    Args:
        seq:    Read sequence string (R1 or R2).
        primers: List of primer sequences to match against.

    Returns:
        0-based index of the best-matching primer, or -1 if no primer is
        within MAX_MISMATCHES of the read prefix.
    """
    head = seq[:PREFIX_LEN]
    best_i, best_mm = -1, MAX_MISMATCHES + 1
    for i, primer in enumerate(primers):
        mm = hamming(head, primer[:PREFIX_LEN])
        if mm < best_mm:
            best_mm, best_i = mm, i
    return best_i if best_mm <= MAX_MISMATCHES else -1


def iter_reads(path):
    """Yield read sequences from a FASTQ or gzipped FASTQ file.

    Args:
        path: Path to a .fastq or .fastq.gz file.

    Yields:
        Sequence string for each read (second line of each FASTQ record).
    """
    opener = gzip.open if path.endswith(".gz") else open
    with opener(path, "rt") as fh:
        while True:
            if not fh.readline():
                break
            seq = fh.readline().strip()
            fh.readline()
            fh.readline()
            yield seq


def count_assignments(r1_path, r2_path):
    """Count read pairs assigned to each amplicon in a FASTQ pair.

    Tries to assign each pair by matching R1 against forward primers first,
    then R2 against reverse primers as fallback.

    Args:
        r1_path: Path to R1 FASTQ (or .fastq.gz) file.
        r2_path: Path to R2 FASTQ (or .fastq.gz) file.

    Returns:
        Tuple of (counts, unassigned) where counts is a list of per-amplicon
        read-pair counts (same order as AMPLICONS) and unassigned is the
        number of pairs that could not be assigned.
    """
    fwd_primers = [a["fwd"] for a in AMPLICONS]
    rev_primers = [a["rev"] for a in AMPLICONS]
    counts = [0] * len(AMPLICONS)
    unassigned = 0
    for r1_seq, r2_seq in zip(iter_reads(r1_path), iter_reads(r2_path)):
        amp_i = assign_amplicon(r1_seq, fwd_primers)
        if amp_i == -1:
            amp_i = assign_amplicon(r2_seq, rev_primers)
        if amp_i == -1:
            unassigned += 1
        else:
            counts[amp_i] += 1
    return counts, unassigned


def main(all_r1, all_r2, unmap_r1, unmap_r2, out_path):
    """Compute per-amplicon unmapped rates and write a LaTeX table.

    Args:
        all_r1:   Path to R1 FASTQ of all read pairs in the library.
        all_r2:   Path to R2 FASTQ of all read pairs in the library.
        unmap_r1: Path to R1 FASTQ of unmapped read pairs only.
        unmap_r2: Path to R2 FASTQ of unmapped read pairs only.
        out_path: Destination path for the generated .tex table file.
    """
    print("Counting assignments in all reads ...", file=sys.stderr)
    total_counts, total_unassigned = count_assignments(all_r1, all_r2)

    print("Counting assignments in unmapped reads ...", file=sys.stderr)
    unmap_counts, unmap_unassigned = count_assignments(unmap_r1, unmap_r2)

    total_all   = sum(total_counts) + total_unassigned
    total_unmap = sum(unmap_counts) + unmap_unassigned

    lines = [
        r"% Auto-generated by pipeline/scripts/amplicon_unmapped_rate.py — do not edit manually.",
        r"\begin{table}[H]",
        r"\centering",
        r"\begin{tabular}{lrrr}",
        r"\toprule",
        r"\textbf{Amplicon} & \textbf{Total pairs} & \textbf{Unmapped pairs} & \textbf{\% unmapped} \\",
        r"\midrule",
    ]

    for i, amp in enumerate(AMPLICONS):
        pct = 100.0 * unmap_counts[i] / total_counts[i] if total_counts[i] else 0.0
        bold_open  = r"\textbf{" if pct > 50 else ""
        bold_close = r"}"        if pct > 50 else ""
        lines.append(
            f"{amp['name']} & {total_counts[i]:,} & {unmap_counts[i]:,} & "
            f"{bold_open}{pct:.1f}\\%{bold_close} \\\\"
        )

    u_pct = 100.0 * unmap_unassigned / total_unassigned if total_unassigned else 0.0
    t_pct = 100.0 * total_unmap / total_all if total_all else 0.0

    lines += [
        r"\midrule",
        f"Unassigned & {total_unassigned:,} & {unmap_unassigned:,} & {u_pct:.1f}\\% \\\\",
        r"\midrule",
        f"\\textbf{{Total}} & \\textbf{{{total_all:,}}} & \\textbf{{{total_unmap:,}}} & \\textbf{{{t_pct:.1f}\\%}} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{Per-amplicon unmapped rate. \emph{Total pairs} is the number of read"
        r" pairs assigned to each amplicon (or unassigned) across the whole library;"
        r" \emph{Unmapped pairs} is the subset of those pairs that failed to align to"
        r" hg19. The \% unmapped column is the fraction of each amplicon's read pairs"
        r" that are unmapped. Amplicon~2 has a markedly higher unmapped rate, consistent"
        r" with aberrant PCR products from its high-GC reverse primer.}",
        r"\label{tab:amplicon-unmapped-rate}",
        r"\end{table}",
    ]

    with open(out_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"Written: {out_path}", file=sys.stderr)


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("all_r1")
    parser.add_argument("all_r2")
    parser.add_argument("unmapped_r1")
    parser.add_argument("unmapped_r2")
    parser.add_argument("out")
    args = parser.parse_args()
    main(args.all_r1, args.all_r2, args.unmapped_r1, args.unmapped_r2, args.out)
