#!/usr/bin/env python3
"""
amplicon_exon_overlap_table.py
Generate a LaTeX table showing how each amplicon spans its target EGFR exon,
including the flanking intronic regions on each side.

Inputs:
  - UCSC hg19 refFlat table  (for EGFR exon coordinates)
  - amplicons.bed             (BLAST-derived amplicon coordinates)

Usage: amplicon_exon_overlap_table.py <refFlat.txt> <amplicons.bed> <out.tex>
"""
import sys

CANONICAL    = "NM_005228"
TARGET_EXONS = [18, 19, 20, 21]


def parse_refflat(path, transcript):
    """Return exon coordinates for a specific transcript from a UCSC refFlat file.

    Args:
        path:       Path to the UCSC hg19 refFlat flat-file table.
        transcript: RefSeq accession to extract (e.g. 'NM_005228').

    Returns:
        List of (exon_start, exon_end) tuples in ascending coordinate order
        (0-based half-open, BED convention).

    Raises:
        ValueError: If the transcript is not found in the file.
    """
    with open(path) as fh:
        for line in fh:
            parts = line.strip().split("\t")
            if len(parts) < 11 or parts[1] != transcript:
                continue
            starts = [int(x) for x in parts[9].rstrip(",").split(",")]
            ends   = [int(x) for x in parts[10].rstrip(",").split(",")]
            return list(zip(starts, ends))
    raise ValueError(f"Transcript {transcript} not found in {path}")


def parse_bed(path):
    """Parse a BED file into a dict mapping amplicon name to (start, end).

    Args:
        path: Path to a BED file with at least four columns
              (chrom, start, end, name).

    Returns:
        Dict mapping name (column 4) to (start, end) integer tuple.
    """
    records = {}
    with open(path) as fh:
        for line in fh:
            if not line.strip() or line.startswith("#"):
                continue
            parts = line.strip().split("\t")
            records[parts[3]] = (int(parts[1]), int(parts[2]))
    return records


def fmt(n):
    """Format an integer with LaTeX-safe thousands separators ({,}).

    Args:
        n: Integer to format.

    Returns:
        String with thousands groups separated by '{,}' for LaTeX math mode.
    """
    return f"{n:,}".replace(",", "{,}")


def main(refflat_path, bed_path, out_path):
    """Generate a LaTeX table of amplicon–exon overlap coordinates.

    Args:
        refflat_path: Path to the UCSC hg19 refFlat table.
        bed_path:     Path to amplicons.bed (BLAST-derived amplicon coordinates).
        out_path:     Destination path for the generated .tex table file.
    """
    exons    = parse_refflat(refflat_path, CANONICAL)
    amplicons = parse_bed(bed_path)

    # Build rows: match each target exon to the amplicon that contains it
    rows = []
    for ex_num in TARGET_EXONS:
        es, ee = exons[ex_num - 1]
        # Find the amplicon that overlaps this exon
        match = None
        for amp_name, (as_, ae) in amplicons.items():
            if es < ae and ee > as_:
                match = (amp_name, as_, ae)
                break
        if match is None:
            continue
        amp_name, as_, ae = match
        amp_label = amp_name.replace("_", "~")
        left_flank  = es - as_
        right_flank = ae - ee
        rows.append((amp_label, ex_num, as_, ae, ae - as_, es, ee, ee - es,
                     left_flank, right_flank))

    with open(out_path, "w") as fh:
        fh.write("% Auto-generated by pipeline/scripts/amplicon_exon_overlap_table.py\n")
        fh.write("% via rule amplicon_exon_overlap_table\n")
        fh.write("\\begin{table}[H]\n")
        fh.write("\\centering\n")
        fh.write("\\small\n")
        fh.write("\\begin{tabular}{clrrrrrr}\n")
        fh.write("\\toprule\n")
        fh.write(
            "\\textbf{Exon} & \\textbf{Amplicon} & "
            "\\textbf{Amp.~start} & \\textbf{Amp.~end} & \\textbf{Amp.~len} & "
            "\\textbf{Exon start} & \\textbf{Exon end} & \\textbf{Exon len} \\\\\n"
        )
        fh.write(" & & & & \\textbf{(bp)} & & & \\textbf{(bp)} \\\\\n")
        fh.write("\\midrule\n")

        for amp_label, ex_num, as_, ae, amp_len, es, ee, ex_len, lf, rf in rows:
            fh.write(
                f"{ex_num} & {amp_label} & "
                f"{fmt(as_)} & {fmt(ae)} & {amp_len} & "
                f"{fmt(es)} & {fmt(ee)} & {ex_len} \\\\\n"
            )

        fh.write("\\bottomrule\n")
        fh.write("\\end{tabular}\n")
        fh.write(
            "\\caption{Amplicon spans relative to their target EGFR exon "
            "(NM\\_005228, hg19, plus strand, 0-based half-open coordinates). "
            "Each amplicon fully contains its target exon; the primers are "
            "placed in the flanking intronic sequence on either side. "
            "Left intronic flank = exon~start $-$ amplicon~start; "
            "right intronic flank = amplicon~end $-$ exon~end.}\n"
        )
        fh.write("\\label{tab:amplicon-exon-overlap}\n")
        fh.write("\\end{table}\n")

    print(f"Written: {out_path}", file=sys.stderr)


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <refFlat.txt> <amplicons.bed> <out.tex>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2], sys.argv[3])
