#!/usr/bin/env python3
"""
blast_gene_intersect_table.py
Parse bedtools intersect -wo output and render a LaTeX table showing which
genes each BLAST amplicon overlaps and by how many bases.

Input: output of:
  bedtools intersect -a amplicons.bed -b hg19_genes.bed -wo

Columns: amp_chr amp_start amp_end amp_name . amp_strand
         gene_chr gene_start gene_end gene_name . gene_strand
         overlap_bp

Usage: blast_gene_intersect_table.py <intersect.txt> <out.tex>
"""
import sys
from collections import defaultdict


def main(intersect_path, out_path):
    """Parse a bedtools intersect output and write a gene-overlap LaTeX table.

    Args:
        intersect_path: Path to the output of
                        ``bedtools intersect -a amplicons.bed -b hg19_genes.bed -wo``.
                        Expected columns: amp fields (0–5), gene fields (6–11),
                        overlap_bp (12).
        out_path:       Destination path for the generated .tex table file.
    """
    # amp_name -> list of (gene_name, amp_len, overlap_bp)
    hits = defaultdict(list)
    seen = set()   # deduplicate (amp, gene) pairs keeping max overlap

    with open(intersect_path) as fh:
        for line in fh:
            if not line.strip():
                continue
            parts = line.strip().split("\t")
            amp_name   = parts[3]
            amp_start  = int(parts[1])
            amp_end    = int(parts[2])
            gene_name  = parts[9]
            overlap_bp = int(parts[12])
            amp_len    = amp_end - amp_start

            key = (amp_name, gene_name)
            if key in seen:
                continue
            seen.add(key)
            hits[amp_name].append((gene_name, amp_len, overlap_bp))

    # Sort amplicons and genes
    amp_order = sorted(hits.keys())

    with open(out_path, "w") as fh:
        fh.write("% Auto-generated by pipeline/scripts/blast_gene_intersect_table.py\n")
        fh.write("% via rule blast_gene_intersect\n")
        fh.write("\\begin{table}[H]\n")
        fh.write("\\centering\n")
        fh.write("\\begin{tabular}{llrrr}\n")
        fh.write("\\toprule\n")
        fh.write(
            "\\textbf{Amplicon} & \\textbf{Gene} & "
            "\\textbf{Amp.\ len (bp)} & "
            "\\textbf{Overlap (bp)} & "
            "\\textbf{Overlap (\\%)} \\\\\n"
        )
        fh.write("\\midrule\n")

        for amp_name in amp_order:
            gene_hits = sorted(hits[amp_name], key=lambda x: -x[2])
            for i, (gene, amp_len, overlap) in enumerate(gene_hits):
                amp_label = amp_name.replace("_", "~") if i == 0 else ""
                pct = f"{100 * overlap / amp_len:.1f}"
                fh.write(
                    f"{amp_label} & {gene} & "
                    f"{amp_len} & {overlap} & {pct} \\\\\n"
                )
            if amp_name != amp_order[-1]:
                fh.write("\\addlinespace[3pt]\n")

        fh.write("\\bottomrule\n")
        fh.write("\\end{tabular}\n")
        fh.write(
            "\\caption{Gene overlaps for the four BLAST-defined amplicon intervals "
            "(Table~\\ref{tab:blast-primers-relaxed}), computed with "
            "\\texttt{bedtools intersect -wo} against the hg19 RefFlat gene "
            "annotation. Overlap is reported in base pairs and as a percentage "
            "of the amplicon length.}\n"
        )
        fh.write("\\label{tab:blast-gene-intersect}\n")
        fh.write("\\end{table}\n")

    print(f"Written: {out_path}", file=sys.stderr)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <intersect.txt> <out.tex>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])
