#!/usr/bin/env python3
"""
Parse blastn -outfmt 6 output for primer sequences and write a LaTeX table
linking each amplicon ID to its hg19 genomic coordinates.

Input columns (outfmt 6 + sstrand):
  qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore sstrand

Usage: python blast_primer_table.py <blast_out.txt> <output.tex>
"""
import sys
from collections import defaultdict

from blast_utils import parse_blast_hits


def parse_blast(path):
    """Parse blastn -outfmt 6 output and group hits by amplicon and orientation.

    Args:
        path: Path to the BLAST tabular output file. Query names must follow the
              convention '<amplicon_id>_fwd' or '<amplicon_id>_rev'
              (e.g. 'amplicon1_fwd').

    Returns:
        Dict mapping amplicon_id (str) to a sub-dict with keys 'fwd' and/or 'rev',
        each holding a hit dict with keys: chrom, left, right, strand, pident, evalue.
    """
    flat = parse_blast_hits(path)
    hits = defaultdict(dict)
    for qseqid, hit in flat.items():
        amp_id, orient = qseqid.rsplit("_", 1)
        hits[amp_id][orient] = hit
    return hits


def main(blast_path, out_path):
    """Generate a LaTeX primer localisation table from BLAST results.

    Args:
        blast_path: Path to the BLAST tabular output file.
        out_path:   Destination path for the generated .tex table file.
    """
    hits = parse_blast(blast_path)

    # Determine amplicon span: fwd primer start to rev primer end (on same chrom)
    rows = []
    for amp_id in sorted(hits.keys()):
        h = hits[amp_id]
        fwd = h.get("fwd")
        rev = h.get("rev")

        chrom      = (fwd or rev)["chrom"]
        amp_start  = fwd["left"]  if fwd else "—"
        amp_end    = rev["right"] if rev else "—"
        fwd_pident = f"{fwd['pident']:.0f}\\%" if fwd else "no hit"
        rev_pident = f"{rev['pident']:.0f}\\%" if rev else "no hit"

        if isinstance(amp_start, int) and isinstance(amp_end, int):
            length = f"{amp_end - amp_start:,}\\,bp"
        else:
            length = "—"

        rows.append((amp_id, chrom, amp_start, amp_end, length, fwd_pident, rev_pident))

    lines = [
        "% Auto-generated by pipeline/scripts/blast_primer_table.py — do not edit manually.",
        r"\begin{table}[H]",
        r"\centering",
        r"\begin{tabular}{lllllll}",
        r"\toprule",
        r"\textbf{Amplicon} & \textbf{Chr} & \textbf{Start (hg19)} & \textbf{End (hg19)}"
        r" & \textbf{Length} & \textbf{Fwd id.} & \textbf{Rev id.} \\",
        r"\midrule",
    ]

    for amp_id, chrom, start, end, length, fwd_id, rev_id in rows:
        amp_label = amp_id.replace("amplicon", "Amplicon ")
        start_str = f"{start:,}" if isinstance(start, int) else start
        end_str   = f"{end:,}"   if isinstance(end,   int) else end
        chrom_str = chrom if chrom.startswith("chr") else f"chr{chrom}"
        lines.append(
            f"\\texttt{{{amp_label}}} & \\texttt{{{chrom_str}}} & {start_str} & {end_str}"
            f" & {length} & {fwd_id} & {rev_id} \\\\"
        )

    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{Primer localisation by \texttt{blastn} against hg19"
        r" (\texttt{-task blastn-short}, \texttt{-perc\_identity 90},"
        r" \texttt{-evalue 1e-3}). Start and End define the amplicon span"
        r" from forward primer start to reverse primer end. ``Fwd id.'' and"
        r" ``Rev id.'' are the percent identity of the best BLAST hit;"
        r" ``no hit'' indicates the primer fell below the E-value threshold.}",
        r"\label{tab:blast-primers}",
        r"\end{table}",
    ]

    with open(out_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"Written: {out_path}", file=sys.stderr)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <blast_out.txt> <output.tex>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])
