#!/usr/bin/env python3
"""
Generate a complete primer localisation table by combining strict and permissive
BLAST results.

For primers found in the strict search the strict hit is used.
For primers missing from the strict search (e.g. amplicon3_rev, E=0.003 > 1e-3
threshold), the best hit from the permissive search is used and marked with a
dagger (†) footnote.

Usage: blast_primer_table_relaxed.py <strict.txt> <permissive.txt> <output.tex>
"""
import sys

from blast_utils import parse_blast_hits


def main(strict_path, permissive_path, out_path):
    """Generate a complete primer localisation LaTeX table from strict + permissive BLAST.

    Primers found in the strict search use their strict hit. Primers missing from the
    strict search fall back to the permissive hit, marked with a dagger footnote.

    Args:
        strict_path:     Path to the strict BLAST output (high-stringency hits).
        permissive_path: Path to the permissive BLAST output (fallback hits).
        out_path:        Destination path for the generated .tex table file.
    """
    strict = parse_blast_hits(strict_path)
    permissive = parse_blast_hits(permissive_path)

    # Determine all amplicon IDs from both sources
    all_primers = set(strict) | set(permissive)
    amp_ids = sorted({p.rsplit("_", 1)[0] for p in all_primers})

    rows = []
    has_relaxed = False

    for amp_id in amp_ids:
        fwd_key = f"{amp_id}_fwd"
        rev_key = f"{amp_id}_rev"

        fwd = strict.get(fwd_key) or permissive.get(fwd_key)
        rev = strict.get(rev_key) or permissive.get(rev_key)

        fwd_relaxed = fwd_key not in strict and fwd_key in permissive
        rev_relaxed = rev_key not in strict and rev_key in permissive
        if fwd_relaxed or rev_relaxed:
            has_relaxed = True

        chrom     = (fwd or rev)["chrom"]
        amp_start = fwd["left"]  if fwd else None
        amp_end   = rev["right"] if rev else None

        def id_str(hit, relaxed):
            if hit is None:
                return "no hit"
            s = f"{hit['pident']:.0f}\\%"
            return s + "$^\\dagger$" if relaxed else s

        fwd_id = id_str(fwd, fwd_relaxed)
        rev_id = id_str(rev, rev_relaxed)

        length = f"{amp_end - amp_start:,}\\,bp" if amp_start and amp_end else "—"

        rows.append((amp_id, chrom, amp_start, amp_end, length, fwd_id, rev_id))

    lines = [
        "% Auto-generated by pipeline/scripts/blast_primer_table_relaxed.py",
        r"\begin{table}[H]",
        r"\centering",
        r"\begin{tabular}{lllllll}",
        r"\toprule",
        r"\textbf{Amplicon} & \textbf{Chr} & \textbf{Start (hg19)} & \textbf{End (hg19)}"
        r" & \textbf{Length} & \textbf{Fwd id.} & \textbf{Rev id.} \\",
        r"\midrule",
    ]

    for amp_id, chrom, start, end, length, fwd_id, rev_id in rows:
        amp_label = amp_id.replace("amplicon", "Amplicon ")
        start_str = f"{start:,}" if start else "—"
        end_str   = f"{end:,}"   if end   else "—"
        chrom_str = chrom if chrom.startswith("chr") else f"chr{chrom}"
        lines.append(
            f"\\texttt{{{amp_label}}} & \\texttt{{{chrom_str}}} & {start_str} & {end_str}"
            f" & {length} & {fwd_id} & {rev_id} \\\\"
        )

    dagger_note = (
        r" $^\dagger$~Hit recovered from the permissive off-target search"
        r" (\texttt{-evalue~1}; Table~\ref{tab:blast-offtarget});"
        r" E-value just exceeded the strict $10^{-3}$ cutoff."
        if has_relaxed else ""
    )

    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{Complete primer localisation combining the strict search"
        r" (\texttt{-evalue~1e-3}) and the permissive off-target search."
        r" All four amplicons are resolved to chr7 (EGFR), including Amplicon~3"
        r" whose reverse primer was below the strict E-value threshold."
        + dagger_note + "}",
        r"\label{tab:blast-primers-relaxed}",
        r"\end{table}",
    ]

    with open(out_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"Written: {out_path}", file=sys.stderr)


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <strict.txt> <permissive.txt> <output.tex>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2], sys.argv[3])
