#!/usr/bin/env python3
"""
Parse a Cutadapt JSON report and write a LaTeX table snippet.
Usage: python cutadapt_table.py <report.json> <output.tex>
"""
import json
import sys


def pct(part, total):
    """Format a count as a LaTeX-escaped percentage string.

    Args:
        part:  Numerator count.
        total: Denominator count.

    Returns:
        LaTeX percentage string (e.g. '12.3\\%'), or 'N/A' if total is zero.
    """
    return f"{100 * part / total:.1f}\\%" if total else "N/A"


def fmt(n):
    """Format an integer with thousands separators, or 'N/A' for None.

    Args:
        n: Integer to format, or None.

    Returns:
        Formatted string with commas (e.g. '1,234,567'), or 'N/A'.
    """
    return f"{n:,}" if n is not None else "N/A"


def main(json_path, tex_path):
    """Parse a Cutadapt JSON report and write a LaTeX summary table.

    Args:
        json_path: Path to the Cutadapt JSON output file.
        tex_path:  Destination path for the generated .tex table file.
    """
    with open(json_path) as f:
        d = json.load(f)

    rc = d["read_counts"]
    bp = d["basepair_counts"]

    total_pairs   = rc["input"]
    r1_with_adp   = rc["read1_with_adapter"]
    r2_with_adp   = rc["read2_with_adapter"]
    too_short     = rc["filtered"]["too_short"]
    passing       = rc["output"]
    qual_trimmed  = bp["quality_trimmed"]
    total_bp      = bp["input"]

    adp1_seq = d["adapters_read1"][0]["three_prime_end"]["sequence"]
    adp2_seq = d["adapters_read2"][0]["three_prime_end"]["sequence"]

    rows = [
        ("Total read pairs processed",          fmt(total_pairs),  ""),
        ("Read~1 with Adaptor~1 detected",       fmt(r1_with_adp),  f"({pct(r1_with_adp, total_pairs)})"),
        ("Read~2 with Adaptor~2 detected",       fmt(r2_with_adp),  f"({pct(r2_with_adp, total_pairs)})"),
        ("Pairs discarded (too short)",          fmt(too_short),    f"({pct(too_short, total_pairs)})"),
        ("Pairs written (passing filters)",      fmt(passing),      f"({pct(passing, total_pairs)})"),
        ("Total bases quality-trimmed",          fmt(qual_trimmed), f"({pct(qual_trimmed, total_bp)})"),
    ]

    lines = [
        "% Auto-generated by pipeline/scripts/cutadapt_table.py — do not edit manually.",
        "\\begin{table}[H]",
        "\\centering",
        "\\begin{tabular}{lrr}",
        "\\toprule",
        "\\textbf{Metric} & \\textbf{Count} & \\textbf{Fraction} \\\\",
        "\\midrule",
    ]
    for label, count, fraction in rows:
        lines.append(f"{label} & {count} & {fraction} \\\\")
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{Cutadapt~\\cite{martin2011} adapter trimming summary for the paired-end MiSeq dataset.",
        f"  Adaptor~1 (\\texttt{{{adp1_seq}}}) trimmed from R1;",
        f"  Adaptor~2 (\\texttt{{{adp2_seq}}}) trimmed from R2.}}",
        "\\label{tab:cutadapt}",
        "\\end{table}",
    ]

    with open(tex_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Written: {tex_path}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <report.json> <output.tex>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])
