#!/usr/bin/env python3
"""
egfr_exon_table.py
Generate a LaTeX table of EGFR kinase-domain exons (18-21) with hg19
coordinates extracted from the UCSC refFlat table, paired with the
known somatic mutations associated with each exon.

Usage: egfr_exon_table.py <refFlat.txt> <out.tex>
"""
import sys

CANONICAL  = "NM_005228"
TARGET_EXONS = [18, 19, 20, 21]

# Known mutation descriptions per exon (static clinical annotation)
MUTATIONS = {
    18: (r"G719X point mutations; uncommon ($\sim$3\% of EGFR mutations), "
         r"sensitive to afatinib and osimertinib"),
    19: (r"In-frame deletions (e.g.\ E746\_A750del); most common EGFR "
         r"alteration ($\sim$45\%), strongly sensitive to EGFR TKIs"),
    20: (r"In-frame insertions; generally confer resistance to "
         r"first/second-generation TKIs; targeted by amivantamab and "
         r"mobocertinib"),
    21: (r"L858R point mutation (c.2573T$>$G); second most common "
         r"EGFR alteration ($\sim$40\%), sensitive to EGFR TKIs"),
}

# Amplicon assigned to each exon (from BLAST primer localisation)
AMPLICON = {18: "Amplicon~2", 19: "Amplicon~1", 20: "Amplicon~4", 21: "Amplicon~3"}


def parse_refflat(path, transcript):
    """Return exon intervals for a transcript from a UCSC refFlat file.

    Args:
        path:       Path to the UCSC hg19 refFlat flat-file table.
        transcript: RefSeq accession to extract (e.g. 'NM_005228').

    Returns:
        List of (exon_start, exon_end) tuples in ascending coordinate order
        (0-based half-open, BED convention).

    Raises:
        ValueError: If the transcript is not found in the file.
    """
    with open(path) as fh:
        for line in fh:
            parts = line.strip().split("\t")
            if len(parts) < 11 or parts[1] != transcript:
                continue
            starts = [int(x) for x in parts[9].rstrip(",").split(",")]
            ends   = [int(x) for x in parts[10].rstrip(",").split(",")]
            return list(zip(starts, ends))
    raise ValueError(f"Transcript {transcript} not found in {path}")


def fmt(n):
    """Format an integer with LaTeX-safe thousands separators ({,}).

    Args:
        n: Integer to format.

    Returns:
        String with thousands groups separated by '{,}' (e.g. '55{,}242{,}465').
    """
    s = f"{n:,}"
    return s.replace(",", "{,}")


def main(refflat_path, out_path):
    """Generate a LaTeX table of EGFR kinase-domain exon coordinates and mutations.

    Args:
        refflat_path: Path to the UCSC hg19 refFlat table.
        out_path:     Destination path for the generated .tex table file.
    """
    exons = parse_refflat(refflat_path, CANONICAL)

    with open(out_path, "w") as fh:
        fh.write("% Auto-generated by pipeline/scripts/egfr_exon_table.py\n")
        fh.write("% via rule egfr_exon_table\n")
        fh.write("\\begin{table}[H]\n")
        fh.write("\\centering\n")
        fh.write("\\small\n")
        fh.write("\\resizebox{\\textwidth}{!}{%\n")
        fh.write("\\begin{tabular}{cclrrp{7cm}}\n")
        fh.write("\\toprule\n")
        fh.write(
            "\\textbf{Exon} & \\textbf{Amplicon} & "
            "\\textbf{Start (hg19)} & \\textbf{End (hg19)} & "
            "\\textbf{Len (bp)} & \\textbf{Known somatic mutations} \\\\\n"
        )
        fh.write("\\midrule\n")

        for ex_num in TARGET_EXONS:
            idx   = ex_num - 1
            start, end = exons[idx]
            length = end - start
            mut    = MUTATIONS[ex_num]
            amp    = AMPLICON[ex_num]
            fh.write(
                f"{ex_num} & {amp} & {fmt(start)} & {fmt(end)} & "
                f"{length} & {mut} \\\\\n"
            )
            if ex_num != TARGET_EXONS[-1]:
                fh.write("\\addlinespace[3pt]\n")

        fh.write("\\bottomrule\n")
        fh.write("\\end{tabular}%\n")
        fh.write("}% end resizebox\n")
        fh.write(
            "\\caption{EGFR kinase-domain exons targeted by the amplicon panel "
            "(NM\\_005228, hg19, plus strand). Coordinates are 0-based half-open "
            "(BED convention), derived from the UCSC hg19 refFlat table. "
            "Exons~18--21 together account for $\\gtrsim$85\\% of all oncogenic EGFR "
            "mutations and are the primary predictive biomarkers for tyrosine kinase "
            "inhibitor (TKI) therapy in non-small-cell lung cancer "
            "(NSCLC)~\\cite{lynch2004}.}\n"
        )
        fh.write("\\label{tab:egfr-exons}\n")
        fh.write("\\end{table}\n")

    print(f"Written: {out_path}", file=sys.stderr)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <refFlat.txt> <out.tex>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])
