#!/usr/bin/env python3
"""
Parse FastQC summary.txt files from zip archives and write a LaTeX table.
Usage: python fastqc_table.py <raw_r1.zip> <raw_r2.zip> <trimmed_r1.zip> <trimmed_r2.zip> <output.tex>
"""
import sys
import zipfile

# Modules flagged as expected artefacts in amplicon sequencing
EXPECTED_FAIL = {
    "Per base sequence content",
    "Per sequence GC content",
    "Sequence Duplication Levels",
    "Overrepresented sequences",
}

STATUS_TEX = {
    "PASS": r"\textcolor{green!60!black}{\textbf{pass}}",
    "WARN": r"\textcolor{orange!80!black}{\textbf{warn}}",
    "FAIL": r"\textcolor{red}{\textbf{fail}}",
}


def parse_summary(zip_path):
    """Return ordered list of (module, status) pairs from a FastQC zip archive.

    Args:
        zip_path: Path to a FastQC result .zip file containing summary.txt.

    Returns:
        List of (module_name, status) tuples (e.g. [('Basic Statistics', 'PASS'), ...]).
        Returns an empty list if summary.txt is not found in the archive.
    """
    with zipfile.ZipFile(zip_path) as zf:
        for name in zf.namelist():
            if name.endswith("/summary.txt"):
                rows = []
                for line in zf.read(name).decode().strip().splitlines():
                    parts = line.split("\t")
                    if len(parts) >= 2:
                        rows.append((parts[1].strip(), parts[0].strip()))
                return rows
    return []


def fmt(status, module):
    """Format a FastQC status for LaTeX, adding a footnote marker for expected failures.

    Args:
        status: FastQC status string ('PASS', 'WARN', or 'FAIL').
        module: FastQC module name (used to detect expected failures).

    Returns:
        LaTeX-coloured status string, with '$^{*}$' appended for expected fail modules.
    """
    tex = STATUS_TEX.get(status.upper(), status.lower())
    if status.upper() == "FAIL" and module in EXPECTED_FAIL:
        tex += r"$^{*}$"
    return tex


def main(raw_r1, raw_r2, trim_r1, trim_r2, out_path):
    """Parse FastQC summary files and write a combined LaTeX quality table.

    Args:
        raw_r1:   Path to the FastQC .zip for raw R1 reads.
        raw_r2:   Path to the FastQC .zip for raw R2 reads.
        trim_r1:  Path to the FastQC .zip for trimmed R1 reads.
        trim_r2:  Path to the FastQC .zip for trimmed R2 reads.
        out_path: Destination path for the generated .tex table file.
    """
    sources = [
        ("Raw R1",  raw_r1),
        ("Raw R2",  raw_r2),
        ("Trim R1", trim_r1),
        ("Trim R2", trim_r2),
    ]

    data = {}
    module_order = []
    for label, path in sources:
        rows = parse_summary(path)
        if not module_order:
            module_order = [m for m, _ in rows]
        data[label] = {m: s for m, s in rows}

    lines = [
        "% Auto-generated by pipeline/scripts/fastqc_table.py — do not edit manually.",
        r"\begin{table}[H]",
        r"\centering",
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"\textbf{Module} & \textbf{Raw R1} & \textbf{Raw R2} "
        r"& \textbf{Trim R1} & \textbf{Trim R2} \\",
        r"\midrule",
    ]

    for module in module_order:
        cells = " & ".join(
            fmt(data[label].get(module, "---"), module)
            for label, _ in sources
        )
        lines.append(f"{module} & {cells} \\\\")

    lines += [
        r"\bottomrule",
        r"\multicolumn{5}{l}{\footnotesize $^{*}$ Expected artefact in amplicon sequencing"
        r" --- not a quality concern (see text).} \\",
        r"\end{tabular}",
        r"\caption{FastQC quality-control summary for raw and adapter-trimmed reads."
        r" Fail flags marked $^{*}$ are expected artefacts of targeted amplicon sequencing"
        r" and do not indicate a quality problem.}",
        r"\label{tab:fastqc}",
        r"\end{table}",
    ]

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Written: {out_path}")


if __name__ == "__main__":
    if len(sys.argv) != 6:
        print(f"Usage: {sys.argv[0]} <raw_r1.zip> <raw_r2.zip> <trimmed_r1.zip> <trimmed_r2.zip> <output.tex>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
