#!/usr/bin/env python3
"""
flagstat_table.py
Parse samtools flagstat output and render a LaTeX table of key mapping metrics.

Usage: flagstat_table.py <flagstat.txt> <out.tex>
"""
import re
import sys


def parse_flagstat(path):
    """Parse a samtools flagstat output file into a dict of metrics.

    Args:
        path: Path to the samtools flagstat output text file.

    Returns:
        Dict mapping metric label (str) to (count, pct_or_None) tuples, where
        count is an int and pct_or_None is a float percentage or None when the
        flagstat line does not include a percentage.
    """
    metrics = {}
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            # Format: "<N> + <M> <label> (<pct>% : ...)" or without pct
            m = re.match(r"(\d+) \+ \d+ (.+?)(?:\s+\(([0-9.]+)%.*\))?$", line)
            if m:
                count = int(m.group(1))
                label = m.group(2).strip()
                pct   = float(m.group(3)) if m.group(3) else None
                metrics[label] = (count, pct)
    return metrics


def fmt(n):
    """Format an integer with thousands separators.

    Args:
        n: Integer to format.

    Returns:
        String with comma-separated thousands groups (e.g. '1,234,567').
    """
    return f"{n:,}"


def main(flagstat_path, out_path):
    """Parse samtools flagstat output and write a LaTeX mapping-statistics table.

    Args:
        flagstat_path: Path to the samtools flagstat output text file.
        out_path:      Destination path for the generated .tex table file.
    """
    m = parse_flagstat(flagstat_path)

    total     = m["in total (QC-passed reads + QC-failed reads)"][0]
    mapped    = m["mapped"][0]
    unmapped  = total - mapped
    pct_map   = 100.0 * mapped   / total if total else 0.0
    pct_unmap = 100.0 * unmapped / total if total else 0.0

    paired      = m.get("paired in sequencing",  (0, None))[0]
    prop_paired = m.get("properly paired",        (0, None))
    singletons  = m.get("singletons",             (0, None))
    diff_chr    = m.get("with mate mapped to a different chr", (0, None))
    duplicates  = m.get("duplicates",             (0, None))[0]

    def row(label, count, pct=None):
        pct_str = f"{pct:.2f}\\%" if pct is not None else "---"
        return f"  {label} & {fmt(count)} & {pct_str} \\\\"

    lines = [
        r"% Auto-generated by pipeline/scripts/flagstat_table.py",
        r"% via rule task3_flagstat_table.",
        r"\begin{table}[H]",
        r"  \centering",
        r"  \begin{tabular}{lrr}",
        r"    \toprule",
        r"    \textbf{Metric} & \textbf{Reads} & \textbf{\%} \\",
        r"    \midrule",
        row("Total reads",      total,    100.00),
        row("Mapped",           mapped,   pct_map),
        row("Unmapped",         unmapped, pct_unmap),
        row("Properly paired",  prop_paired[0],
            prop_paired[1] if prop_paired[1] is not None
            else 100.0 * prop_paired[0] / total if total else 0.0),
        row("Singletons",       singletons[0],
            singletons[1] if singletons[1] is not None
            else 100.0 * singletons[0] / total if total else 0.0),
        row("Mate on diff.\ chr ($\\geq$MQ5)",
            diff_chr[0],
            100.0 * diff_chr[0] / total if total else 0.0),
        row("Duplicates",       duplicates, 0.00),
        r"    \bottomrule",
        r"  \end{tabular}",
        r"  \caption{%",
        r"    Mapping statistics from \texttt{samtools flagstat}.",
        r"    Percentages are relative to the total number of reads.",
        r"    Duplicate marking was not performed (\textit{duplicates} = 0).",
        r"  }",
        r"  \label{tab:flagstat}",
        r"\end{table}",
    ]

    with open(out_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")

    # Summary to stderr
    print(f"Total reads : {fmt(total)}", file=sys.stderr)
    print(f"Mapped      : {fmt(mapped)} ({pct_map:.2f}%)", file=sys.stderr)
    print(f"Unmapped    : {fmt(unmapped)} ({pct_unmap:.2f}%)", file=sys.stderr)
    print(f"Written: {out_path}", file=sys.stderr)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <flagstat.txt> <out.tex>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])
