#!/usr/bin/env python3
"""
Parse bedtools intersect output and write a LaTeX table of covered amplicon regions.

Expected input: output of
    bedtools intersect -a amplicons.bed -b hg19_genes.bed -wa -wb
Columns: amp_chrom, amp_start, amp_end, gene_chrom, gene_start, gene_end, gene_name, score, strand

Usage: python gene_region_table_bedtools.py <intersect.bed> <output.tex>
"""
import sys
from collections import defaultdict


def parse_intersect(path):
    """
    Return list of (chrom, start, end, genes_str) sorted by chrom/start.
    Aggregates gene names per amplicon interval.
    """
    regions = defaultdict(set)  # (chrom, start, end) -> {gene_names}
    with open(path) as fh:
        for line in fh:
            parts = line.strip().split("\t")
            if len(parts) < 7:
                continue
            chrom, start, end = parts[0], int(parts[1]), int(parts[2])
            gene = parts[6]
            if gene:
                regions[(chrom, start, end)].add(gene)

    rows = []
    for (chrom, start, end), genes in regions.items():
        chrom_ucsc = chrom if chrom.startswith("chr") else f"chr{chrom}"
        rows.append((chrom_ucsc, start, end, ", ".join(sorted(genes))))

    return sorted(rows, key=lambda r: (r[0], r[1]))


def main(intersect_path, out_path):
    rows = parse_intersect(intersect_path)
    if not rows:
        print(f"ERROR: no rows parsed from {intersect_path}", file=sys.stderr)
        sys.exit(1)

    lines = [
        "% Auto-generated by pipeline/scripts/gene_region_table_bedtools.py — do not edit manually.",
        r"\begin{table}[H]",
        r"\centering",
        r"\begin{tabular}{llll}",
        r"\toprule",
        r"\textbf{Chr} & \textbf{Start (hg19)} & \textbf{End (hg19)} & \textbf{Gene(s)} \\",
        r"\midrule",
    ]

    for chrom, start, end, genes in rows:
        lines.append(
            f"\\texttt{{{chrom}}} & {start:,} & {end:,} & \\textit{{{genes}}} \\\\"
        )

    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{Amplicon regions covered by the BAM (\texttt{bedtools genomecov} "
        r"$\to$ \texttt{bedtools merge}), annotated against hg19 RefFlat gene models "
        r"(\texttt{bedtools intersect}). Start and End are the exact covered-base "
        r"boundaries as reported by \texttt{bedtools merge}.}",
        r"\label{tab:gene-regions}",
        r"\end{table}",
    ]

    with open(out_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"Written: {out_path}", file=sys.stderr)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <intersect.bed> <output.tex>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])
