#!/usr/bin/env python3
"""
Compute the on-target rate for an amplicon panel and write a LaTeX table.

Steps:
  1. Read total mapped reads from samtools flagstat output.
  2. Count on-target reads via bedtools intersect -u | samtools view -c.
  3. Write a LaTeX table with total, on-target, and off-target counts.

Usage: on_target_rate.py <bam> <amplicons.bed> <flagstat.txt> <output.tex>
"""
import re
import subprocess
import sys
import tempfile
import os


def read_total_mapped(flagstat_path):
    """Parse samtools flagstat output to extract the total mapped read count.

    Args:
        flagstat_path: Path to the samtools flagstat output text file.

    Returns:
        Total number of mapped reads (int).

    Raises:
        ValueError: If no mapped-read line is found in the file.
    """
    with open(flagstat_path) as fh:
        for line in fh:
            if "mapped (" in line:
                return int(line.split()[0])
    raise ValueError(f"Could not find mapped read count in {flagstat_path}")


def count_on_target(bam, bed):
    """Count reads overlapping any amplicon region using bedtools intersect.

    Strips the 'chr' prefix from the BED file so chromosome names match
    the BAM's NCBI-style naming convention (e.g. '7' instead of 'chr7').
    Each read is counted at most once even if it overlaps multiple amplicons.

    Args:
        bam: Path to the input BAM file.
        bed: Path to the amplicons BED file (may use chr-prefixed names).

    Returns:
        Number of on-target reads (int).
    """
    with tempfile.NamedTemporaryFile(mode="w", suffix=".bed", delete=False) as tmp:
        with open(bed) as fh:
            for line in fh:
                tmp.write(re.sub(r"^chr", "", line))
        tmp_path = tmp.name

    try:
        result = subprocess.run(
            f"bedtools intersect -a {bam} -b {tmp_path} -u | samtools view -c",
            shell=True, capture_output=True, text=True, check=True,
        )
        return int(result.stdout.strip())
    finally:
        os.unlink(tmp_path)


def write_table(total, on_target, out_path):
    """Write a LaTeX table summarising on-target and off-target read counts.

    Args:
        total:     Total number of mapped reads (int).
        on_target: Number of on-target reads (int).
        out_path:  Destination path for the generated .tex table file.

    Returns:
        None.
    """
    off_target = total - on_target
    pct_on  = 100 * on_target  / total if total else 0.0
    pct_off = 100 * off_target / total if total else 0.0

    lines = [
        "% Auto-generated by pipeline/scripts/on_target_rate.py — do not edit manually.",
        r"\begin{table}[H]",
        r"\centering",
        r"\begin{tabular}{lrr}",
        r"\toprule",
        r"\textbf{Category} & \textbf{Reads} & \textbf{\%} \\",
        r"\midrule",
        f"Total mapped   & {total:,}      & 100.0 \\\\",
        f"On-target      & {on_target:,}  & {pct_on:.1f} \\\\",
        f"Off-target     & {off_target:,} & {pct_off:.1f} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{On-target rate: fraction of mapped reads falling within the",
        r"four BLAST-defined EGFR amplicon spans (\texttt{amplicons.bed}).",
        r"On-target reads were counted using \texttt{bedtools intersect -u};",
        r"each read is counted at most once regardless of how many amplicons it",
        r"overlaps.}",
        r"\label{tab:on-target-rate}",
        r"\end{table}",
    ]

    with open(out_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def main(bam, bed, flagstat, out_path):
    """Compute on-target rate and write a LaTeX summary table.

    Args:
        bam:      Path to the input BAM file.
        bed:      Path to the amplicons BED file.
        flagstat: Path to the samtools flagstat output file.
        out_path: Destination path for the generated .tex table file.

    Returns:
        None.
    """
    total     = read_total_mapped(flagstat)
    on_target = count_on_target(bam, bed)
    off_target = total - on_target

    print(f"Total mapped : {total:,}", file=sys.stderr)
    print(f"On-target    : {on_target:,} ({100*on_target/total:.1f}%)", file=sys.stderr)
    print(f"Off-target   : {off_target:,} ({100*off_target/total:.1f}%)", file=sys.stderr)

    write_table(total, on_target, out_path)
    print(f"Written: {out_path}", file=sys.stderr)


if __name__ == "__main__":
    if len(sys.argv) != 5:
        print(f"Usage: {sys.argv[0]} <bam> <amplicons.bed> <flagstat.txt> <output.tex>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
