#!/usr/bin/env python3
"""
Per-amplicon read-through statistics.

Assigns each read pair to one of the 4 amplicons by matching the primer
sequence at the start of R1 (forward primer) or R2 (reverse primer), then
checks whether the read also contains the far-adapter RC sequence (read-through).

Usage: python per_amplicon_readthrough.py <r1.fastq.gz> <r2.fastq.gz> <output.tex>
"""
import gzip
import sys

AMPLICONS = [
    {
        "name": "Amplicon 1",
        "fwd":  "TTGCCAGTTAACGTCTTCCTTCTCTCTCTG",
        "rev":  "GAGAAAAGGTGGGCCTGAGGTTCAGAGCCA",
    },
    {
        "name": "Amplicon 2",
        "fwd":  "CCCTTGTCTCTGTGTTCTTGTCCCCCCCA",
        "rev":  "CCCCACCAGACCATGAGAGGCCCTGCGGCC",
    },
    {
        "name": "Amplicon 3",
        "fwd":  "TGATCTGTCCCTCACAGCAGGGTCTTCTCT",
        "rev":  "TGACCTAAAGCCACCTCCTTA",
    },
    {
        "name": "Amplicon 4",
        "fwd":  "CACACTGACGTGCCTCTCCCTCCCTCCA",
        "rev":  "CCGTATCTCCCTTCCCTGATTA",
    },
]

# Read-through signals: RC of far adapter (confirmed by check_adaptors.py)
ADP2_RC = "TGGAGAACAGTGACGATCGC"  # dominant in R1 (read-through into Adp2)
ADP1_RC = "TGGAGATGCTGCCGAGTCTT"  # dominant in R2 (read-through into Adp1)

MAX_MISMATCHES = 2   # allowed mismatches in primer / adapter matching
PREFIX_LEN     = 20  # use first N bases of each primer for amplicon assignment


def hamming(a, b):
    """Count mismatches between two equal-length strings."""
    return sum(x != y for x, y in zip(a, b))


def assign_amplicon(seq, primers):
    """
    Return 0-based amplicon index whose primer best matches the start of seq,
    or -1 if no primer is within MAX_MISMATCHES of the first PREFIX_LEN bases.
    """
    head = seq[:PREFIX_LEN]
    best_i, best_mm = -1, MAX_MISMATCHES + 1
    for i, primer in enumerate(primers):
        pref = primer[:PREFIX_LEN]
        mm = hamming(head, pref)
        if mm < best_mm:
            best_mm, best_i = mm, i
    return best_i if best_mm <= MAX_MISMATCHES else -1


def has_readthrough(seq, adapter):
    """
    Return True if adapter is found anywhere in seq after position 50,
    within MAX_MISMATCHES mismatches.
    """
    alen = len(adapter)
    region = seq[50:]
    for start in range(len(region) - alen + 1):
        if hamming(region[start:start + alen], adapter) <= MAX_MISMATCHES:
            return True
    return False


def iter_reads(path):
    """Yield read sequences from a FASTQ or gzipped FASTQ file.

    Args:
        path: Path to a .fastq or .fastq.gz file.

    Yields:
        Sequence string for each read (second line of each FASTQ record).
    """
    opener = gzip.open if path.endswith(".gz") else open
    with opener(path, "rt") as fh:
        while True:
            header = fh.readline()
            if not header:
                break
            seq  = fh.readline().strip()
            fh.readline()   # +
            fh.readline()   # quality
            yield seq


def main(r1_path, r2_path, out_path):
    """Compute per-amplicon read-through statistics and write a LaTeX table.

    Args:
        r1_path:  Path to R1 FASTQ (or .fastq.gz) file.
        r2_path:  Path to R2 FASTQ (or .fastq.gz) file.
        out_path: Destination path for the generated .tex table file.
    """
    fwd_primers = [a["fwd"] for a in AMPLICONS]
    rev_primers = [a["rev"] for a in AMPLICONS]
    n = len(AMPLICONS)

    r1_total = [0] * n
    r1_rt    = [0] * n
    r2_total = [0] * n
    r2_rt    = [0] * n
    unassigned = 0

    for r1_seq, r2_seq in zip(iter_reads(r1_path), iter_reads(r2_path)):
        # Try forward primer in R1 first, fall back to reverse primer in R2
        amp_i = assign_amplicon(r1_seq, fwd_primers)
        if amp_i == -1:
            amp_i = assign_amplicon(r2_seq, rev_primers)
        if amp_i == -1:
            unassigned += 1
            continue

        r1_total[amp_i] += 1
        if has_readthrough(r1_seq, ADP2_RC):
            r1_rt[amp_i] += 1

        r2_total[amp_i] += 1
        if has_readthrough(r2_seq, ADP1_RC):
            r2_rt[amp_i] += 1

    total_pairs = sum(r1_total) + unassigned

    # ------------------------------------------------------------------ LaTeX
    def pct_tex(count, total):
        p = 100.0 * count / total if total else 0.0
        color = "red" if p > 15 else ("orange!80!black" if p > 5 else "green!60!black")
        return f"\\textcolor{{{color}}}{{{p:.1f}\\%}}"

    def fmt_n(n):
        return f"{n:,}"

    lines = [
        "% Auto-generated by pipeline/scripts/per_amplicon_readthrough.py — do not edit manually.",
        r"\begin{table}[H]",
        r"\centering",
        r"\begin{tabular}{lrrrrr}",
        r"\toprule",
        r"\textbf{Amplicon} & \textbf{Read pairs} & \textbf{R1 RT} & \textbf{R1 RT\,\%}"
        r" & \textbf{R2 RT} & \textbf{R2 RT\,\%} \\",
        r"\midrule",
    ]

    for i, amp in enumerate(AMPLICONS):
        r1p = pct_tex(r1_rt[i], r1_total[i])
        r2p = pct_tex(r2_rt[i], r2_total[i])
        lines.append(
            f"{amp['name']} & {fmt_n(r1_total[i])} & {fmt_n(r1_rt[i])} & {r1p}"
            f" & {fmt_n(r2_rt[i])} & {r2p} \\\\"
        )

    unassigned_pct = 100.0 * unassigned / total_pairs if total_pairs else 0.0
    lines += [
        r"\midrule",
        f"Unassigned & {fmt_n(unassigned)} & --- & --- & --- & --- \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{Per-amplicon read-through statistics. "
        r"RT = reads containing the far-adapter reverse complement at their 3' end, "
        r"indicating the read length exceeded the insert size. "
        r"Colour coding: \textcolor{green!60!black}{$<$5\%} (amplicon longer than read), "
        r"\textcolor{orange!80!black}{5--15\%} (borderline), "
        r"\textcolor{red}{$>$15\%} (amplicon shorter than read length). "
        f"Unassigned: {fmt_n(unassigned)} pairs ({unassigned_pct:.1f}\\%)"
        r" --- reads whose 5' end did not match any known primer within "
        f"{MAX_MISMATCHES} mismatches." + "}",
        r"\label{tab:per-amplicon-readthrough}",
        r"\end{table}",
    ]

    with open(out_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"Written: {out_path}")


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <r1.fastq.gz> <r2.fastq.gz> <output.tex>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2], sys.argv[3])
