#!/usr/bin/env python3
"""
primer_assignment_table.py
Assigns each read pair to one of the four amplicons by matching the first
PREFIX_LEN bases of R1 (forward primer) or R2 (reverse primer) against the
known primer sequences (up to MAX_MISMATCHES mismatches).

Outputs a LaTeX table summarising the assignment rate per amplicon,
which confirms that primer sequences are present at the expected position
in each read.

Usage:
    primer_assignment_table.py <r1.fastq.gz> <r2.fastq.gz> <output.tex>
"""
import gzip
import sys

AMPLICONS = [
    {"name": "Amplicon 1",
     "fwd": "TTGCCAGTTAACGTCTTCCTTCTCTCTCTG",
     "rev": "GAGAAAAGGTGGGCCTGAGGTTCAGAGCCA"},
    {"name": "Amplicon 2",
     "fwd": "CCCTTGTCTCTGTGTTCTTGTCCCCCCCA",
     "rev": "CCCCACCAGACCATGAGAGGCCCTGCGGCC"},
    {"name": "Amplicon 3",
     "fwd": "TGATCTGTCCCTCACAGCAGGGTCTTCTCT",
     "rev": "TGACCTAAAGCCACCTCCTTA"},
    {"name": "Amplicon 4",
     "fwd": "CACACTGACGTGCCTCTCCCTCCCTCCA",
     "rev": "CCGTATCTCCCTTCCCTGATTA"},
]

MAX_MISMATCHES = 2
PREFIX_LEN     = 20


def hamming(a, b):
    """Count mismatches between two strings up to the length of the shorter one.

    Args:
        a: First sequence string.
        b: Second sequence string.

    Returns:
        Number of positions where the characters differ.
    """
    return sum(x != y for x, y in zip(a, b))


def assign_amplicon(seq, primers):
    """Assign a read to the best-matching primer by Hamming distance on the prefix.

    Args:
        seq:    Read sequence string.
        primers: List of primer sequences to match against.

    Returns:
        0-based index of the best-matching primer within MAX_MISMATCHES, or
        -1 if no primer matched within the threshold.
    """
    head = seq[:PREFIX_LEN]
    best_i, best_mm = -1, MAX_MISMATCHES + 1
    for i, primer in enumerate(primers):
        mm = hamming(head, primer[:PREFIX_LEN])
        if mm < best_mm:
            best_mm, best_i = mm, i
    return best_i if best_mm <= MAX_MISMATCHES else -1


def iter_reads(path):
    """Yield read sequences from a FASTQ or gzipped FASTQ file.

    Args:
        path: Path to a .fastq or .fastq.gz file.

    Yields:
        Sequence string for each read (second line of each FASTQ record).
    """
    opener = gzip.open if path.endswith(".gz") else open
    with opener(path, "rt") as fh:
        while True:
            if not fh.readline():
                break
            seq = fh.readline().strip()
            fh.readline()
            fh.readline()
            yield seq


def main(r1_path, r2_path, out_path, caption=None, label=None):
    """Assign read pairs to amplicons and write a LaTeX primer-assignment table.

    Args:
        r1_path: Path to R1 FASTQ (or .fastq.gz) file.
        r2_path: Path to R2 FASTQ (or .fastq.gz) file.
        out_path: Destination path for the generated .tex table file.
        caption: Optional LaTeX caption string (uses DEFAULT_CAPTION if None).
        label:   Optional LaTeX label string (uses DEFAULT_LABEL if None).
    """
    if caption is None:
        caption = DEFAULT_CAPTION
    if label is None:
        label = DEFAULT_LABEL
    fwd_primers = [a["fwd"] for a in AMPLICONS]
    rev_primers = [a["rev"] for a in AMPLICONS]
    counts = [0] * len(AMPLICONS)
    unassigned = 0

    for r1_seq, r2_seq in zip(iter_reads(r1_path), iter_reads(r2_path)):
        amp_i = assign_amplicon(r1_seq, fwd_primers)
        if amp_i == -1:
            amp_i = assign_amplicon(r2_seq, rev_primers)
        if amp_i == -1:
            unassigned += 1
        else:
            counts[amp_i] += 1

    total = sum(counts) + unassigned

    lines = [
        "% Auto-generated by pipeline/scripts/primer_assignment_table.py — do not edit manually.",
        r"\begin{table}[H]",
        r"\centering",
        r"\begin{tabular}{llrr}",
        r"\toprule",
        r"\textbf{Amplicon} & \textbf{Forward primer (first 20\,bp)} & \textbf{Read pairs} & \textbf{\%} \\",
        r"\midrule",
    ]

    for i, amp in enumerate(AMPLICONS):
        pct = 100.0 * counts[i] / total if total else 0.0
        primer_prefix = amp["fwd"][:PREFIX_LEN]
        lines.append(
            f"{amp['name']} & \\texttt{{{primer_prefix}}} & {counts[i]:,} & {pct:.1f}\\% \\\\"
        )

    upct = 100.0 * unassigned / total if total else 0.0
    lines += [
        r"\midrule",
        f"Unassigned & --- & {unassigned:,} & {upct:.1f}\\% \\\\",
        r"\midrule",
        f"\\textbf{{Total}} & & \\textbf{{{total:,}}} & \\textbf{{100.0\\%}} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        r"\end{table}",
    ]

    with open(out_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"Written: {out_path}", file=sys.stderr)


DEFAULT_CAPTION = (
    r"Primer assignment rates. Each read pair was assigned to an amplicon by"
    r" matching the first 20\,bp of R1 against the known forward primer sequences"
    r" (up to 2 mismatches); if no match was found in R1, R2 was matched against the"
    r" reverse primer sequences. The assignment rate per amplicon confirms that primer"
    r" sequences are present at the expected 5' position of the reads."
    r" Unassigned pairs are reads whose 5' end did not match any known primer."
)
DEFAULT_LABEL = "tab:primer-assignment"


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("r1")
    parser.add_argument("r2")
    parser.add_argument("out")
    parser.add_argument("--caption", default=DEFAULT_CAPTION)
    parser.add_argument("--label",   default=DEFAULT_LABEL)
    args = parser.parse_args()
    main(args.r1, args.r2, args.out, caption=args.caption, label=args.label)
