#!/usr/bin/env python3
"""
primer_properties_table.py
Compute GC content and melting temperature (Tm) for all 8 primers and
render a LaTeX table.

Tm is calculated using the nearest-neighbour thermodynamic model
(SantaLucia 1998, PNAS 95:1460) with a salt correction for 50 mM NaCl
and a primer concentration of 250 nM -- the same conditions assumed by
Primer3 and most primer design tools.

Usage: primer_properties_table.py <config.yaml> <out.tex>
"""
import sys
import math

# ── Nearest-neighbour parameters (SantaLucia 1998, Table 2) ─────────────────
# Keys: 5'→3' dinucleotide on the top strand
# Values: (ΔH kcal/mol, ΔS cal/mol/K)
NN_PARAMS = {
    "AA": (-7.9, -22.2), "AT": (-7.2, -20.4), "TA": (-7.2, -21.3),
    "CA": (-8.5, -22.7), "GT": (-8.4, -22.4), "CT": (-7.8, -21.0),
    "GA": (-8.2, -22.2), "CG": (-10.6, -27.2), "GC": (-9.8, -24.4),
    "GG": (-8.0, -19.9),
    # Complements (handled by symmetry below)
    "TT": (-7.9, -22.2), "TG": (-8.5, -22.7), "AC": (-8.4, -22.4),
    "AG": (-7.8, -21.0), "TC": (-8.2, -22.2),
    "CC": (-8.0, -19.9),
}

# Initiation parameters (SantaLucia 1998, Table 2)
INIT_GC = (0.1, -2.8)    # terminal G or C
INIT_AT = (2.3,  4.1)    # terminal A or T

R   = 1.987    # gas constant, cal / (mol · K)
CT  = 250e-9   # total strand concentration (250 nM)
NA  = 0.05     # NaCl concentration (50 mM)


def gc_content(seq):
    """Compute the GC content of a DNA sequence as a percentage.

    Args:
        seq: DNA sequence string (case-insensitive).

    Returns:
        GC content as a float percentage (0–100).
    """
    seq = seq.upper()
    gc = sum(1 for b in seq if b in "GC")
    return 100 * gc / len(seq)


def tm_nearest_neighbour(seq):
    """Return the melting temperature (Tm) in °C using the SantaLucia 1998 model.

    Uses nearest-neighbour thermodynamic parameters with a salt correction for
    50 mM NaCl and a primer concentration of 250 nM.

    Args:
        seq: DNA primer sequence string (case-insensitive, 5'→3').

    Returns:
        Melting temperature in degrees Celsius (float).
    """
    seq = seq.upper()
    dH, dS = 0.0, 0.0

    # Initiation
    for end in (seq[0], seq[-1]):
        if end in "GC":
            dH += INIT_GC[0]; dS += INIT_GC[1]
        else:
            dH += INIT_AT[0]; dS += INIT_AT[1]

    # Nearest-neighbour stacking
    for i in range(len(seq) - 1):
        dinuc = seq[i:i+2]
        if dinuc in NN_PARAMS:
            h, s = NN_PARAMS[dinuc]
            dH += h; dS += s

    dH_cal = dH * 1000   # convert kcal → cal

    # Tm in Kelvin (non-self-complementary; CT/4 for two strands)
    tm_K = dH_cal / (dS + R * math.log(CT / 4))

    # Salt correction: ΔTm = 16.6 × log10([Na+])
    tm_C = tm_K - 273.15 + 16.6 * math.log10(NA)
    return tm_C


def parse_config(path):
    """Parse forward and reverse primer sequences from config.yaml.

    Uses a minimal hand-written parser to avoid a PyYAML dependency in Docker.
    Reads list items under the 'primers.forward' and 'primers.reverse' keys.

    Args:
        path: Path to pipeline/config.yaml.

    Returns:
        Tuple of (fwd_primers, rev_primers) where each is a list of sequence
        strings in amplicon order (Amplicon 1 first).
    """
    fwd, rev = [], []
    section = None
    with open(path) as fh:
        for line in fh:
            stripped = line.strip()
            if stripped.startswith("forward:"):
                section = "fwd"
            elif stripped.startswith("reverse:"):
                section = "rev"
            elif stripped.startswith("- ") and section in ("fwd", "rev"):
                seq = stripped[2:].split("#")[0].strip()
                if seq:
                    (fwd if section == "fwd" else rev).append(seq)
            elif stripped and not stripped.startswith("#") and ":" in stripped:
                if not stripped.startswith("-"):
                    section = None   # left primers block
    return fwd, rev


def main(config_path, out_path):
    """Compute primer properties and write a LaTeX table.

    Args:
        config_path: Path to pipeline/config.yaml (for primer sequences).
        out_path:    Destination path for the generated .tex table file.
    """
    fwd, rev = parse_config(config_path)
    n = max(len(fwd), len(rev))

    rows = []
    for i in range(n):
        for strand, seqs in (("fwd", fwd), ("rev", rev)):
            if i >= len(seqs):
                continue
            seq = seqs[i]
            gc  = gc_content(seq)
            tm  = tm_nearest_neighbour(seq)
            rows.append((i + 1, strand, seq, len(seq), gc, tm))

    with open(out_path, "w") as fh:
        fh.write("% Auto-generated by pipeline/scripts/primer_properties_table.py\n")
        fh.write("% via rule primer_properties_table\n")
        fh.write("\\begin{table}[H]\n")
        fh.write("\\centering\n")
        fh.write("\\small\n")
        fh.write("\\begin{tabular}{clp{6.8cm}rrc}\n")
        fh.write("\\toprule\n")
        fh.write(
            "\\textbf{Amp.} & \\textbf{Strand} & \\textbf{Sequence (5$'\\to$3$'$)} & "
            "\\textbf{Len} & \\textbf{GC\\%} & \\textbf{T$_\\mathrm{m}$ (\\textdegree C)} \\\\\n"
        )
        fh.write("\\midrule\n")

        for i, (amp, strand, seq, length, gc, tm) in enumerate(rows):
            strand_label = "fwd" if strand == "fwd" else "rev"
            fh.write(
                f"{amp} & {strand_label} & \\texttt{{{seq}}} & "
                f"{length} & {gc:.1f} & {tm:.1f} \\\\\n"
            )
            # Spacer between amplicons
            if i < len(rows) - 1 and rows[i + 1][0] != amp:
                fh.write("\\addlinespace[3pt]\n")

        fh.write("\\bottomrule\n")
        fh.write("\\end{tabular}\n")
        fh.write(
            "\\caption{Primer properties for the four EGFR amplicons. "
            "GC content and melting temperature T$_\\mathrm{m}$ were computed "
            "from the primer sequences in \\texttt{config.yaml} using the "
            "nearest-neighbour thermodynamic model (SantaLucia 1998) with "
            "50\\,mM NaCl and 250\\,nM primer concentration.}\n"
        )
        fh.write("\\label{tab:primer-properties}\n")
        fh.write("\\end{table}\n")

    # Print summary to stderr for inspection
    print(f"{'Amp':>4} {'Strand':>6} {'Len':>4} {'GC%':>6} {'Tm':>6}", file=sys.stderr)
    for amp, strand, seq, length, gc, tm in rows:
        print(f"{amp:>4} {strand:>6} {length:>4} {gc:>6.1f} {tm:>6.1f}", file=sys.stderr)
    print(f"Written: {out_path}", file=sys.stderr)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <config.yaml> <out.tex>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])
